- id: '1648256024121'
  alias: Reggeli információk
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hipad_xpro_kepernyo
    to: 'on'
  - platform: state
    entity_id: light.tablet_screen
    to: 'on'
  condition:
  - condition: state
    entity_id: group.family_all
    state: home
  - condition: state
    entity_id: light.tablet_screen
    state: 'on'
  - condition: state
    entity_id: input_boolean.reggeli_info
    state: 'on'
  - condition: template
    value_template: '{{ (now().weekday() in (0,1,2,3,4) and now().hour >= 6 and now().hour
      <= 7) or (now().weekday() in (5,6) and now().hour >= 7 and now().hour <= 8)
      }}'
  action:
  - service: number.set_value
    data:
      value: 90
    target:
      entity_id: number.hipad_xpro_kepernyo_kikapcsolasi_idozito
  - service: browser_mod.popup
    data:
      dismissable: false
      autoclose: false
      title: Magyarország eső térkép
      size: fullscreen
      timeout: 60000
      browserID:
      - Tablet
      content:
        type: custom:weather-radar-card
        zoom_level: 8
        static_map: true
        show_scale: true
        map_style: voyager
  - service: script.reggeli_informacio
    data: {}
  - delay:
      seconds: 90
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.reggeli_info
    data: {}
  - service: number.set_value
    data:
      value: 10
    target:
      entity_id: number.hipad_xpro_kepernyo_kikapcsolasi_idozito
  mode: single
  max_exceeded: silent
- id: '1651074945261'
  alias: TTS on door opening with persons at home
  description: ''
  use_blueprint:
    path: MackoMici/tts-door-opening.yaml
    input:
      door_sensor: binary_sensor.sonoff_bejarati_ajto
      minutes: 10
      persons: person.hunyadvari_zoltan, person.szakacs_katalin
      message-single: 'Isten hozott <person>!

        Szia <person>!

        Üdvüzöllek <person>!

        <person> hazajött!'
      message-multiple: Üdvüzlet itthon <persons>!
      persons-concat: ' és '
      target: media_player.u1006_media_player
      actions:
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: script.valaki_hazajott
        data: {}
- id: '1665923714852'
  alias: Párásító világítás kikapcsolás
  description: Ha nincs otthon senki és a párásítót bekapcsoljuk akkor a párásító
    világítst kapcsolja ki.
  trigger:
  - platform: state
    entity_id:
    - fan.aroma_diffuser
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: group.family_wifi
    state: away
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.aroma_diffuser_nightlight
  mode: single
- id: '1673370581948'
  alias: Bathroom Humidity Management
  description: ''
  use_blueprint:
    path: MackoMici/Bathroom_Humidity_Management.yaml
    input:
      humidity_sensor: sensor.furdoszoba_paratartalom
      fan_switch: switch.sonoff_furdo_szelloztetes
      outdoor_absolutehumidity_sensor: sensor.kulteri_absolutehumidity
      reference_humidity_sensor: sensor.belteri_paratartalom
      absolutehumidity_sensor: sensor.furdoszoba_absolutehumidity
      rising_threshold: 15
      falling_threshold: 13
- id: '1676475309119'
  alias: Fürdőszoba fűtés
  description: ''
  use_blueprint:
    path: MackoMici/Switch_timer.yaml
    input:
      switch: switch.sonoff_furdoszoba_futes
      timer: timer.furdoszoba_futes
      inumber: input_number.furdoszoba_futes
- id: '1676475337454'
  alias: Fűtés mindenképp
  description: ''
  use_blueprint:
    path: MackoMici/Switch_timer.yaml
    input:
      switch: input_boolean.futes
      timer: timer.futes_mindenkepp
      inumber: input_number.futes_mindenkepp
- id: '1683179020941'
  alias: Előszoba villany kapcsolás
  description: ''
  use_blueprint:
    path: MackoMici/Door_Sensor_Light.yaml
    input:
      workday: binary_sensor.workday_sensor
      calendar: calendar.unnepnapok_magyarorszag
      doorsensor_entity: binary_sensor.sonoff_bejarati_ajto
      light_switch: switch.sonoff_eloszoba
- id: '1684847787385'
  alias: Otthoni riasztás
  description: ''
  use_blueprint:
    path: MackoMici/home_security.yaml
    input:
      notify_device: 24f3d1348620662fedaf75c1d0977196
      security: alarm_control_panel.gateway_alarm
      family: group.family_all
      doorsensor: binary_sensor.sonoff_bejarati_ajto
- id: '1690287367883'
  alias: Wc frissítő vezérlés
  description: ''
  use_blueprint:
    path: MackoMici/toilet_freshener.yaml
    input:
      doorsensor_entity: binary_sensor.wc_contact
      light_switch: light.wc_main
      freshener_switch: switch.sonoff_illatosito
- id: '1692591387982'
  alias: Kamra világítás vezérlés
  description: ''
  use_blueprint:
    path: MackoMici/chamber_light.yaml
    input:
      season: sensor.season
      doorsensor_entity: binary_sensor.kamra_contact
      doorsensor_light: binary_sensor.kamra_light
      light_switch: light.kamra_main
- id: '1694905706739'
  alias: Ablak nyitásra klíma vezérlés
  description: ''
  use_blueprint:
    path: MackoMici/Climate_window.yaml
    input:
      window_entity: binary_sensor.nappali_ablak_contact
      climate_target: climate.gree_klima
- id: '1694915125006'
  alias: Reggeli információ engedélyezés
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.reggeli_info
  mode: single
- id: '1695389801621'
  alias: Tanusítvány lejárat figyelés
  description: ''
  use_blueprint:
    path: MackoMici/ssl_expiration.yaml
    input:
      certificate_input: sensor.ssl_cert_expiry
      days_input: 21
      notify_device: 24f3d1348620662fedaf75c1d0977196
      time_input: '15:00:00'
- id: '1695642885702'
  alias: Világítás kikapcsolás
  description: ''
  use_blueprint:
    path: MackoMici/lights_off.yaml
    input:
      family: group.family_wifi
      lights: light.vilagitas
      notify_device: 24f3d1348620662fedaf75c1d0977196
- id: '1695652594042'
  alias: Tablet Charging
  description: ''
  use_blueprint:
    path: MackoMici/tablet_charging.yaml
    input:
      tablet_battery: sensor.hipad_xpro_elem_akku
      tablet_switch: switch.gosund_ep2_tablet_konnektor
      tablet_screen: switch.hipad_xpro_kepernyo
      turn_on: 20
- id: '1696638709773'
  alias: Ajtó nyitásra tablet mozgás érzékelő bekapcsolás
  description: ''
  use_blueprint:
    path: MackoMici/tablet_motion.yaml
    input:
      motion_switch: switch.hipad_xpro_mozgaserzekeles
      camera: camera.tablet
      family: group.family_wifi
      doorsensor: binary_sensor.kamra_contact
