- id: '1640836502892'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: MackoMici/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 15
      exclude:
        entity_id:
        - sensor.u1006_battery_level
        - sensor.sm_a705fn_battery_level
        - sensor.oneplus_a5000_battery_level
      actions:
      - service: notify.zoolesz
        data:
          message: Alacsony {{sensors}} elem.
          title: Elem állapot
- id: '1648256024121'
  alias: Reggeli információk
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.u1006_screen
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: group.family_all
    state: home
  - condition: state
    entity_id: input_boolean.reggeli_info
    state: 'on'
  - condition: template
    value_template: '{{ (now().weekday() in (0,1,2,3,4) and now().hour >= 6 and now().hour
      <= 7) or (now().weekday() in (5,6) and now().hour >= 7 and now().hour <= 8)
      }}'
  action:
  - service: script.reggeli_informacio
    data: {}
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.reggeli_info
  mode: single
- id: '1649997237707'
  alias: Door Sensor Light
  description: ''
  use_blueprint:
    path: MackoMici/Door_Sensor_Light.yaml
    input:
      calendar: calendar.unnepnapok_magyarorszag
      doorsensor_entity: binary_sensor.sonoff_bejarati_ajto
      light_switch: switch.sonoff_eloszoba
      door_closed_wait: 90
- id: '1651074945261'
  alias: TTS on door opening with persons at home
  description: ''
  use_blueprint:
    path: MackoMici/tts-door-opening.yaml
    input:
      door_sensor: binary_sensor.sonoff_bejarati_ajto
      minutes: 10
      persons: person.hunyadvari_zoltan, person.szakacs_katalin
      message-single: 'Isten hozott <person>!

        Szia <person>!

        Üdvüzöllek <person>!

        <person> hazajött!'
      message-multiple: Üdvüzlet itthon <persons>!
      persons-concat: ' és '
      target: media_player.u1006_media_player
      actions:
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: script.valaki_hazajott
        data: {}
- id: '1654312693366'
  alias: Nagging Alerting Notification Automation
  description: ''
  use_blueprint:
    path: MackoMici/nagging_alert_notification.yaml
    input:
      sensor_entity: plant.ficus
      alert_state: problem
      initial_delay: 900
      repeat_delay: 1800
      notify_device: 823be0e7ca2f23eddf6402b3b655ee4e
      resolved_message: A {{ entity_name }} problémája elhárult.
      notify_message: 'Figyelem a {{ entity_name }}-nak problémája van: {{ entity_problem
        }}.'
      dismiss_entity: input_boolean.noveny
      condition_entity: sensor.hunyadvari_zoltan_wifi
      condition_entity_state: home
- id: '1665923714852'
  alias: Párásító világítás kikapcsolás
  description: ''
  trigger:
  - platform: state
    entity_id:
    - humidifier.parasito
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: group.family_wifi
    state: away
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.parasito
  mode: single
- id: '1673370581948'
  alias: Bathroom Humidity Management
  description: ''
  use_blueprint:
    path: MackoMici/Bathroom_Humidity_Management.yaml
    input:
      humidity_sensor: sensor.furdoszoba_paratartalom
      fan_switch: switch.sonoff_furdo_szelloztetes
      outdoor_absolutehumidity_sensor: sensor.kulteri_absolutehumidity
      reference_humidity_sensor: sensor.belteri_paratartalom
      absolutehumidity_sensor: sensor.furdoszoba_absolutehumidity
      rising_threshold: 15
      falling_threshold: 13
- id: '1673530275257'
  alias: SSL expiry notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  condition: []
  action:
  - service: notify.zoolesz
    data:
      message: Az SSL tanúsítvány 21 nap múlva lejár, és nem újult meg automatikusan
      title: Figyelmeztetés!!!
  mode: single
- id: '1673609887095'
  alias: Hibák Keresése
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: watchman.report
    data: {}
  mode: single
- id: '1676475309119'
  alias: Fürdőszoba fűtés
  description: ''
  use_blueprint:
    path: MackoMici/Switch_timer.yaml
    input:
      switch: switch.sonoff_furdoszoba_futes
      timer: timer.furdoszoba_futes
      inumber: input_number.furdoszoba_futes
- id: '1676475337454'
  alias: Fűtés mindenképp
  description: ''
  use_blueprint:
    path: MackoMici/Switch_timer.yaml
    input:
      switch: input_boolean.futes
      timer: timer.futes_mindenkepp
      inumber: input_number.futes_mindenkepp
- id: '1680850389335'
  alias: Kamra világítás vezérlés
  description: ''
  use_blueprint:
    path: MackoMici/chamber_light.yaml
    input:
      season: sensor.season
      doorsensor_entity: binary_sensor.kamra_contact
      doorsensor_light: binary_sensor.kamra_light
      light_switch: light.yeelight_colorb_kamra
