# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry

logger:
  default: info
#  logs:
    # log level for HA core
#    homeassistant.core: warning

    # log level for all python scripts
#    homeassistant.components.python_script: warning

#    custom_components.multiscrape: debug

#    homeassistant.components.zha: debug
#    zigpy: debug


http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50
    icon: mdi:home

recorder:
  purge_keep_days: 30

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/ha-floorplan/floorplan.js
      type: module
    - url: /hacsfiles/lovelace-canary/canary.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/scheduler-card/scheduler-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/hass-swipe-navigation/swipe-navigation.js
      type: module
    - url: /hacsfiles/clock-weather-card/clock-weather-card.js
      type: module
    - url: /hacsfiles/lovelace-hourly-weather/hourly-weather.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-flower-card/flower-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module      
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: https://fonts.googleapis.com/css2?family=Oxygen&family=Ubuntu:wght@300&display=swap
      type: css
  dashboards:
    lovelace-floorplan:
      mode: yaml
      filename: floorplan.yaml
      title: Floorplan
      icon: mdi:floor-plan
      show_in_sidebar: true
    lovelace-mobil:
      mode: yaml
      filename: mobil.yaml
      title: Mobil
      icon: mdi:cellphone
      show_in_sidebar: true

homeassistant:
  packages: !include_dir_named include
  customize: !include customize.yaml
  allowlist_external_dirs:
    - "/home/zoolesz/.homeassistant"

#python_script:

gree_ext:

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
#  mode: local
#  reload: always

# Text to speech
tts:
  - platform: microsoft
    api_key: !secret tts_api_key
    language: hu-hu
    type: TamasNeural
    region: westeurope
    rate: -10

stt:
  - platform: google_cloud_stt
    key_file: service_account.json
    model: command_and_search

frontend:
  themes: !include_dir_merge_named themes

#zha:
#  zigpy_config:
#    ota:
#      otau_directory: /home/zoolesz/.homeassistant/zigpy_ota/

#zha_toolkit:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
