# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry

#logger:
#  default: error
#  logs:
    # log level for HA core
#    homeassistant.core: warning

    # log level for all python scripts
#    homeassistant.components.python_script: warning

homeassistant:
  allowlist_external_dirs:
    - /home/homeassistant/.homeassistant

browser_mod:
  prefix: "browser_"

#python_script:

samsungtv_smart:
  - host: 192.168.1.147
    app_list: {
      "Netflix": "3201907018807/org.tizen.netflixapp",
      "Youtube": "111299001912/9Ur5IzDKqV.TizenYouTube",
      "HBO Max": "cj37Ni3qXM.HBONow",
      "Plex": "3201512006963/kIciSQlYEM.plex",
      "TARR MobilTv": "DC80zckKNb.Basicapplication"
    }

lyric:
  client_id: !secret lyric_id
  client_secret: !secret lyric_secret

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

weather:
  - platform: pirateweather
    api_key: !secret pirateweather_api_key
    latitude: !secret location_latitude
    longitude: !secret location_longitude
    mode: hourly
    name: Pirate Weather

  - platform: pirateweather
    api_key: !secret pirateweather_api_key
    latitude: !secret location_latitude
    longitude: !secret location_longitude
    mode: daily
    name: Pirate Weather Daily

vacuum:
  - platform: viomise
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    name: Viomi SE

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
#  mode: local
#  reload: always

binary_sensor:
  - platform: workday
    country: HU
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

template:
  sensor:
    - unique_id: hass_version
      icon: mdi:home-assistant
      state: >
        {{ 'Naprakész' if states('sensor.current_version') == 
        states('sensor.home_assistant_versions') else states('sensor.home_assistant_versions') }}
      attributes:
        friendly_name: >
          Telepítve {{ states('sensor.current_version') }}

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes

sensor: !include sensor.yaml
group: !include groups.yaml
notify: !include notify.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml