decluttering_templates: !include lovelace/decluttering_templates.yaml

views:
  - type: custom:grid-layout
    path: 0
    layout:
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  floorplan  floorplan  floorplan"
        "sidebar  floorplan  floorplan  floorplan"
        "sidebar  floorplan  floorplan  floorplan"
    icon: mdi:floor-plan
    badges: []
    cards:
      - type: custom:floorplan-card
        full_height: true
        style: |
          ha-card {
            box-shadow: none;
            background: none;
          }
        view_layout:
          grid-area: floorplan
        config:
          image: /local/floorplan/House.svg
          stylesheet: /local/floorplan/House.css
          defaults:
            hover_action: hover-info
            tap_action: none
          rules:
            - name: Világítás
              entities:
                - entity: switch.sonoff_haloszoba
                  element: area.haloszoba
                - entity: switch.sonoff_eloszoba
                  element: area.eloszoba
                - entity: switch.sonoff_furdoszoba
                  element: area.furdoszoba
                - entity: light.yeelight_colorb_kamra
                  element: area.raktar
                - entity: light.yeelight_colorb_wc
                  element: area.wc
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'
            - name: Időjárás adatok 1
              entities:
                - sensor.metno_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${(entity.state !== undefined) ? Math.round(entity.state * 10) / 10 + "°C" : "unknown"}'
            - name: Időjárás adatok 2
              entities:
                - sensor.metno_humidity
                - sensor.metno_wind_speed
              state_action:
                - service: floorplan.text_set
                  service_data: '${(entity.state !== undefined) ? Math.round(entity.state * 10) / 10 : "unknown"}'
            - name: Időjárás szöveg
              entities:
                - weather.forecast_home
              state_action:
                - service: floorplan.text_set
                  service_data: |
                    >
                    var strName = '';
                    switch (entity.state) { 
                      case 'clear-night': strName = 'Tiszta este'; break;
                      case 'cloudy': strName = 'Felhős idő'; break;
                      case 'exceptional': strName = 'Extrém idő'; break;
                      case 'fog': strName = 'Köd'; break;
                      case 'hail': strName = 'Jégeső'; break;
                      case 'lightning': strName = 'Vihar'; break;
                      case 'lightning-rainy': strName = 'Viharos eső'; break;
                      case 'partlycloudy': strName = 'Részben felhős idő'; break;
                      case 'pouring': strName = 'Szakadó eső'; break;
                      case 'rainy': strName = 'Esős idő'; break;
                      case 'snowy': strName = 'Havazás'; break;
                      case 'snowy-rainy': strName = 'Havas eső'; break;
                      case 'sunny': strName = 'Napos idő'; break;
                      case 'windy': strName = 'Szeles idő'; break;
                      case 'windy-variant': strName = 'Változóan szeles idő'; break;
                      default: srtName = 'unknown'; break; 
                    } 
                    return strName;
            - name: Időjárás ikon
              entity: weather.forecast_home
              element: weather.condition
              state_action:
                service: floorplan.image_set
                service_data:
                  image: /local/floorplan/weather_icons/${entity.state}.svg
                  cache: true
            - name: Időjárás
              element: things.weather
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: &browser_mod_1080
                      |
                      --popup-min-width: 1080px;
                      --popup-border-width: var(--ha-card-border-width);
                      --popup-border-radius: var(--ha-card-border-radius);
                      --popup-padding-y: -1px;
                    content:
                      type: custom:layout-card
                      layout_type: custom:grid-layout 
                      layout:
                        grid-template-columns: 1fr 2fr
                        grid-template-rows: 1fr
                        grid-template-areas: |
                          "clock radar"
                          "title radar"
                          "daily hourly"
                      cards:
                        !include lovelace/idojaras.yaml
            - name: Hőmérséklet
              entities:
                - sensor.haloszoba_temperature
                - sensor.konyha_temperature
                - sensor.nappali_temperature
                - sensor.ebedlo_temperature
                - sensor.gyerekszoba_temperature
                - sensor.furdoszoba_homerseklet
              state_action:
                - service: floorplan.text_set
                  service_data: '${(entity.state !== undefined) ? Math.round(entity.state * 10) / 10 : "unknown"}'
            - name: Páratartalom
              entities:
                - sensor.haloszoba_humidity
                - sensor.konyha_humidity
                - sensor.nappali_humidity
                - sensor.ebedlo_humidity
                - sensor.gyerekszoba_humidity
                - sensor.furdoszoba_paratartalom
              state_action:
                - service: floorplan.text_set
                  service_data: '${ (entity.state !== undefined) ? Math.round(entity.state * 10) / 10 : "unknown" }'
            - name: Elemek
              entities:
                - sensor.haloszoba_ablak_battery
                - sensor.nappali_ablak_battery
                - sensor.haloszoba_battery
                - sensor.konyha_battery
                - sensor.nappali_battery
                - sensor.ebedlo_battery
                - sensor.gyerekszoba_battery
                - sensor.furdoszoba_battery
                - sensor.furdoszoba_2_battery
                - sensor.bejarati_ajto_battery
              state_action:
                service: floorplan.image_set
                service_data:
                  image: /local/floorplan/battery/battery-${Math.round(entity.state / 10) * 10}.png
                  cache: true
            - name: Szellőztetés
              entity: switch.sonoff_furdo_szelloztetes
              element: switch.furdo_fan
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "spinning" : ""}'
            - name: Klíma
              entity: climate.gree_klima
              element: things.klima
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: &browser_mod_style
                      |
                      --popup-border-width: var(--ha-card-border-width);
                      --popup-border-radius: var(--ha-card-border-radius);
                      --popup-padding-y: -1px;
                    content:
                      type: custom:layout-card
                      layout_type: custom:grid-layout
                      cards:
                        !include lovelace/klima.yaml
              state_action:
                service: floorplan.class_set
                service_data: '${ (entity.state === "off") ? "thing-off" : ((entity.state === "unavailable") ? "thing-unavailable" : "thing-on") }'
            - name: Törölköző
              entity: switch.sonoff_furdoszoba_futes
              element: things.torolkozo
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: '${ (entity.state === "off") ? "thing-off" : ((entity.state === "unavailable") ? "thing-unavailable" : "thing-on") }'
            - name: Fűtés
              entity: climate.honeywell_home_termosztat
              element: things.termosztat
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: *browser_mod_style
                    content:
                      type: custom:layout-card
                      layout_type: custom:grid-layout
                      cards:
                        !include lovelace/futes.yaml
              state_action:
                service: floorplan.class_set
                service_data: '${ (entity.state === "off") ? "thing-off" : ((entity.state === "unavailable") ? "thing-unavailable" : "thing-on") }'
            - name: Növény
              entity: plant.new_zealand_spinach
              element: flora
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: &browser_mod_650
                      |
                      --popup-min-width: 650px;
                      --popup-border-width: var(--ha-card-border-width);
                      --popup-border-radius: var(--ha-card-border-radius);
                      --popup-padding-y: -1px;
                    content:
                      !include lovelace/novenyek.yaml
              state_action:
                service: floorplan.style_set
                service_data:
                  style: >
                    opacity: ${ entity.state === "ok" ? "0" : "1" };
                    fill: ${ entity.state === "ok" ? "" : "#C1424299" };
                    transition: ${ entity.state === "ok" ? "fill 5s ease" : "" };
#            - name: Tablet
#              entity: light.u1006_screen
#              element: tablet
#              tap_action: toggle              
#              state_action:
#                service: floorplan.style_set
#                service_data:
#                  style: >
#                    opacity: ${ entity.state === "on" ? "1" : "0" };
#                    fill: ${ entity.state === "on" ? "#F9D27C99" : "" };
#                    transition: ${ entity.state === "off" ? "fill 5s ease" : "" };
            - name: Párásítás
              entity: fan.aroma_diffuser
              element: things.parasito
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: *browser_mod_style
                    content:
                      type: custom:vertical-stack-in-card
                      cards:
                        !include lovelace/parasitas.yaml
              state_action:
                service: floorplan.class_set
                service_data: '${ (entity.state === "off") ? "thing-off" : ((entity.state === "unavailable") ? "thing-unavailable" : "thing-on") }'
            - name: Tv
              entity: media_player.samsung_q80_series_65
              elements: 
               - things.tv
               - things.arnyek
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: *browser_mod_style
                    content:
                      !include lovelace/tv.yaml
              state_action:
                service: floorplan.class_set
                service_data: '${ (entity.state === "off") ? "thing-off" : ((entity.state === "unavailable") ? "thing-unavailable" : "thing-on") }'
            - name: Binary Sensor
              entities:
               - entity: binary_sensor.sonoff_bejarati_ajto
                 element: bejarat
               - entity: binary_sensor.haloszoba_ablak_contact
                 element: haloszoba_ablak
               - entity: binary_sensor.nappali_ablak_contact
                 element: nappali_ablak
              state_action:
                service: floorplan.class_set
                service_data: '${ (entity.state === "on") ? "binary-sensor-on" : "binary-sensor-off" }'
            - name: Vacuum
              entity: vacuum.viomi_se
              elements:
                - vacuum
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: *browser_mod_style
                    content:
                      type: custom:vertical-stack-in-card
                      cards:
                        !include lovelace/vacuum.yaml
            - name: Information
              elements:
                - information
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: *browser_mod_1080
                    content:
                      type: custom:layout-card
                      layout_type: custom:grid-layout
                      layout:
                        grid-template-columns: repeat(2, 1ft)
                        grid-template-rows: 1fr
                        grid-template-areas: |
                          "HA-title Debian-title"
                          "HA Debian"
                          "Network-title Network-title"
                          "Network-1 Network-2"
                          "Network-1 Network-3"
                      cards:
                        !include lovelace/system.yaml
            - name: Karácsony
              elements:
                - karacsony
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.popup
                  data:
                    style: *browser_mod_style
                    content:
                      type: custom:vertical-stack-in-card
                      cards:
                        !include lovelace/karacsony.yaml
      - !include  lovelace/sidebar.yaml
