decluttering_templates: !include lovelace/decluttering_templates.yaml
apexcharts_card_templates: !include lovelace/apexcharts_card_templates.yaml

swipe_nav:
  animate: swipe
views:
  - path: kezdolap
    icon: mdi:home
    badges: []
    type: custom:vertical-layout
    cards:
      - !include lovelace/fejlec.yaml
      - !include lovelace/home.yaml
  - path: kapcsolo
    icon: mdi:gesture-tap-button
    badges: []
    type: custom:vertical-layout
    cards:
      !include lovelace/kapcsolo.yaml
  - path: futes
    icon: mdi:radiator
    badges: []
    type: custom:vertical-layout
    cards:
      - !include lovelace/fejlec.yaml
      - !include lovelace/futes.yaml
      - !include lovelace/grafikon.yaml
  - path: klima
    icon: mdi:snowflake
    badges: []
    type: custom:vertical-layout
    cards:
      - !include lovelace/fejlec.yaml
      - !include lovelace/klima.yaml
      - !include lovelace/grafikon.yaml
  - path: idojaras
    icon: mdi:weather-partly-snowy-rainy
    badges: []
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "clock"
        "title"
        "hourly"
        "daily"
        "radar"
    cards:
      !include lovelace/idojaras.yaml
  - path: parasitas
    icon: mdi:air-humidifier
    badges: []
    type: custom:vertical-layout
    cards:
      - !include lovelace/fejlec.yaml
      - !include lovelace/parasitas.yaml
  - path: porszivo
    icon: mdi:robot-vacuum
    badges: []
    type: custom:vertical-layout
    cards:
      !include lovelace/vacuum.yaml
  - path: novenyek
    icon: mdi:leaf
    badges: []
    type: custom:vertical-layout
    cards:
      !include lovelace/novenyek.yaml
  - path: tv
    icon: mdi:television
    badges: []
    type: custom:vertical-layout
    cards:
      - !include lovelace/tv.yaml
  - path: karacsony
    icon: mdi:pine-tree
    badges: []
    type: custom:vertical-layout
    cards:
      !include lovelace/karacsony.yaml
  - path: informacio
    icon: mdi:information-outline
    badges: []
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
      grid-template-areas: |
        "HA-title"
        "HA"
        "Debian-title"
        "Debian-1"
        "Debian-2"
        "Network-title"
        "Network-1"
        "Network-2"
        "Network-3"
    cards:
      !include lovelace/system.yaml
  - path: schedule
    icon: mdi:calendar-range
    badges: []
    type: custom:vertical-layout
    subview: true
    cards:
      - !include lovelace/schedule.yaml
