- platform: template
  sensors:
    bejarati_ajto_battery:
      friendly_name: "Bejárati Ajtó elem"
      value_template: >
        {% if states('sensor.sonoff_bejarati_ajto_battery_voltage') != None %}
          {% set max = 3 | int %}
          {% set current = states('sensor.sonoff_bejarati_ajto_battery_voltage') | int %}
          {{ (current/(max/100)) | int }}
        {% endif %}

- platform: abalin_nameday
  country: hu
  time_zone: Europe/Prague

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /mnt/hdd1
    - type: disk_use_percent
      arg: /mnt/hdd2
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

- platform: template
  sensors:
    ha_uptime:
      friendly_name: 'Home Assistant Uptime'
      value_template: >-
        {% set mins = (as_timestamp(now()) - as_timestamp(states('sensor.last_boot'))) | int // 60 %}
        {% set hours = mins // 60 %}
        {% set days = mins // 1440 %}
        {% if days > 1 %}
          {{ days }} napja
        {% elif hours > 1 %}
          {{ hours }} órája
        {% else %}
          {{ mins }} perce
        {% endif %}

- platform: template
  sensors:
    mikrotik_router_uptime:
      value_template: >-
        {% set mins = (as_timestamp(now()) - as_timestamp(states('sensor.mikrotik_uptime'))) | int // 60 %}
        {% set hours = mins // 60 %}
        {% set days = mins // 1440 %}
        {% if days > 1 %}
          {{ days }} napja
        {% elif hours > 1 %}
          {{ hours }} órája
        {% else %}
          {{ mins }} perce
        {% endif %}

- platform: template
  sensors:
    tablet_uptime:
      value_template: >-
        {% set mins = (as_timestamp(now()) - as_timestamp(states('sensor.u1006_last_reboot'))) | int // 60 %}
        {% set hours = mins // 60 %}
        {% set days = mins // 1440 %}
        {% if days > 1 %}
          {{ days }} napja
        {% elif hours > 1 %}
          {{ hours }} órája
        {% else %}
          {{ mins }} perce
        {% endif %}

- platform: template
  sensors:
    week_day:
      value_template: >-
        {%- set days = ['Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek', 'Szombat', 'Vasárnap'] %}
        {{ days[now().weekday()]}}
    current_date:
      value_template: >-
        {%- set months = ['Január', 'Február', 'Március', 'Április', 'Május', 'Június', 'Július', 'Augusztus', 'Szeptember', 'Október', 'November', 'December'] %}
        {{ (now().timestamp() | timestamp_custom('%d, # %Y')).replace('#', months[now().month-1]) }}

- platform: template
  sensors:
    tablet_ram_use:
      value_template: >-
        {% if is_number(states.sensor.u1006_ram_free_memory.state) %}
          {{100 - states.sensor.u1006_ram_free_memory.state | float(0) / (states.sensor.u1006_ram_total_memory.state | float(0) / 100)}}
        {% endif %}
    tablet_storage_use:
      value_template: >-
        {% if is_number(states.sensor.u1006_internal_storage_free_space.state) %}
          {{100 - states.sensor.u1006_internal_storage_free_space.state | float(0) / (states.sensor.u1006_internal_storage_total_space.state | float(0) / 100)}}
        {% endif %}

- platform: time_date
  display_options:
    - time
    - date

- platform: template
  sensors:
    mobil_hunyadvari_zoltan:
      value_template: >-
        {% if states('sensor.oneplus_a5000_wifi_connection') == "MiciMacko 5GHz" %}
          home
        {% else %}
          not_home
        {% endif %}

- platform: template
  sensors:
    mobil_szakacs_katalin:
      value_template: >-
        {% if states('sensor.sm_a705fn_wifi_connection') == "MiciMacko 5GHz" %}
          home
        {% else %}
          not_home
        {% endif %}

- platform: pirateweather
  api_key: !secret pirateweather_api_key
  scan_interval: '00:20:00'
  monitored_conditions:
    - temperature
    - precip_probability
    - precip_type
    - humidity
    - cloud_cover
    - nearest_storm_distance
    - precip_intensity
    - wind_speed

- platform: min_max
  name: Beltéri hőmérséklet
  type: mean
  entity_ids:
    - sensor.ebedlo_temperature
    - sensor.nappali_temperature
    - sensor.indoor_temperature

- platform: min_max
  name: Beltéri páratartalom
  type: mean
  entity_ids:
    - sensor.ebedlo_humidity
    - sensor.nappali_humidity

- platform: min_max
  name: Kültéri hőmérséklet
  type: mean
  entity_ids:
    - sensor.pirateweather_temperature
    - sensor.outdoor_temperature

- platform: min_max
  name: Kültéri páratartalom
  type: mean
  entity_ids:
    - sensor.pirateweather_humidity
    - sensor.outdoor_humidity

- platform: min_max
  name: Fürdőszoba hőmérséklet
  type: mean
  entity_ids:
    - sensor.furdoszoba_temperature
    - sensor.furdoszoba_2_temperature

- platform: min_max
  name: Fürdőszoba páratartalom
  type: mean
  entity_ids:
    - sensor.furdoszoba_humidity
    - sensor.furdoszoba_2_humidity
