views:
  - theme: Backend-selected
    path: default_view
    title: Home
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.honeywell_home_termosztat
          - type: entities
            entities:
              - sensor.setpoint_status
              - sensor.outdoor_humidity
              - sensor.outdoor_temperature
              - sensor.indoor_temperature
              - input_boolean.elofutes
              - input_number.nappali_homerseklet
              - input_number.ejszakai_homerseklet
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.gree_klima
          - type: entities
            entities:
              - switch.gree_klima_fresh_air
              - switch.gree_klima_panel_light
              - switch.gree_klima_quiet
              - switch.gree_klima_xfan
      - type: vertical-stack
        cards:
          - type: alarm-panel
            entity: alarm_control_panel.gateway_alarm
          - type: entities
            entities:
              - select.gateway_data
              - select.gateway_command
      - type: entities
        entities:
          - sensor.ebedlo_temperature
          - sensor.ebedlo_humidity
          - sensor.ebedlo_battery
        title: Ebédlő
      - type: entities
        entities:
          - switch.sonoff_eloszoba
          - binary_sensor.sonoff_bejarati_ajto
          - sensor.sonoff_bejarati_ajto_battery_voltage
        title: Előszoba
      - type: entities
        entities:
          - sensor.furdoszoba_humidity
          - sensor.furdoszoba_temperature
          - sensor.furdoszoba_battery
          - sensor.furdoszoba_2_humidity
          - sensor.furdoszoba_2_temperature
          - sensor.furdoszoba_2_battery
          - entity: sensor.furdoszoba_paratartalom
            icon: mdi:water-percent
          - entity: sensor.furdoszoba_homerseklet
            icon: mdi:thermometer
          - sensor.furdoszoba_absolutehumidity
          - sensor.furdoszoba_dewpoint
          - sensor.furdoszoba_heatindex
          - sensor.furdoszoba_simmerindex
          - sensor.furdoszoba_simmerzone
          - sensor.furdoszoba_perception
          - switch.sonoff_furdoszoba_futes
          - switch.sonoff_furdoszoba
          - switch.sonoff_furdo_szelloztetes
        title: Fürdőszoba
      - type: entities
        entities:
          - sensor.gyerekszoba_humidity
          - sensor.gyerekszoba_temperature
          - sensor.gyerekszoba_battery
        title: Gyerek Szoba
      - type: plant-status
        entity: plant.ficus
      - type: entities
        entities:
          - sensor.haloszoba_temperature
          - sensor.haloszoba_humidity
          - sensor.haloszoba_battery
          - switch.sonoff_haloszoba
          - binary_sensor.haloszoba_ablak_contact
          - binary_sensor.haloszoba_ablak_light
          - sensor.haloszoba_ablak_battery
          - sensor.haloszoba_absolutehumidity
          - sensor.haloszoba_dewpoint
          - sensor.haloszoba_heatindex
          - sensor.haloszoba_simmerindex
          - sensor.haloszoba_simmerzone
          - sensor.haloszoba_perception
        title: Hálószoba
      - type: entities
        entities:
          - sensor.konyha_temperature
          - sensor.konyha_humidity
          - sensor.konyha_battery
        title: Konyha
      - type: entities
        entities:
          - sensor.nappali_temperature
          - sensor.nappali_humidity
          - sensor.nappali_battery
          - binary_sensor.nappali_ablak_contact
          - binary_sensor.nappali_ablak_light
          - sensor.nappali_ablak_battery
        title: Nappali
      - type: entities
        entities:
          - person.hunyadvari_zoltan
          - person.szakacs_katalin
        title: Family
      - type: entities
        entities:
          - binary_sensor.home_assistant_website_update_available
          - sensor.hacs
          - sensor.home_assistant_uptime
          - sensor.home_assistant_website
          - sensor.current_version
        title: System information
#      - type: entities
#        entities:
#          - sensor.tablet_ram_use
#          - sensor.tablet_storage_use
#          - sensor.tablet_uptime
#          - sensor.u1006_battery_level
#          - binary_sensor.u1006_device_admin
#          - binary_sensor.u1006_kiosk_mode
#          - binary_sensor.u1006_plugged_in
#          - button.u1006_bring_to_foreground
#          - button.u1006_load_start_url
#          - button.u1006_reboot_device
#          - button.u1006_restart_browser
#          - button.u1006_send_to_background
#          - switch.u1006_kiosk_lock
#          - switch.u1006_maintenance_mode
#          - switch.u1006_motion_detection
#          - switch.u1006_screensaver
#        title: Tablet
      - type: entities
        entities:
          - entity: sensor.disk_use_percent
            name: System SSD
          - entity: sensor.disk_use_percent_mnt_hdd1
            name: HDD 1
          - entity: sensor.disk_use_percent_mnt_hdd2
            name: HDD2
          - entity: sensor.memory_use_percent
          - entity: sensor.last_boot
          - entity: sensor.processor_temperature
          - entity: sensor.processor_use
        title: Debian Server
      - type: entities
        entities:
          - update.mikrotik_routerboard_firmware_update
          - update.mikrotik_routeros_update
          - sensor.mikrotik_uptime
          - sensor.mikrotik_cpu_load
          - sensor.mikrotik_memory_usage
          - sensor.mikrotik_hdd_usage
          - sensor.mikrotik_wired_clients
          - sensor.mikrotik_wireless_clients
          - switch.mikrotik_port_ether1
          - switch.mikrotik_port_ether2
          - switch.mikrotik_port_ether3
          - switch.mikrotik_port_ether4
          - switch.mikrotik_port_ether5
          - switch.mikrotik_port_wlan1
          - switch.mikrotik_port_wlan2
          - switch.mikrotik_port_pppoe_out1
        title: Mikrotik
      - type: media-control
        entity: media_player.samsung_q80_series_65
      - type: entities
        entities:
          - vacuum.viomi_se
          - input_boolean.ebedlo_takaritas
          - input_datetime.ebedlo_takaritas
          - input_boolean.eloszoba_takaritas
          - input_datetime.eloszoba_takaritas
          - input_boolean.folyoso_takaritas
          - input_datetime.folyoso_takaritas
          - input_boolean.gyerekszoba_takaritas
          - input_datetime.gyerekszoba_takaritas
          - input_boolean.haloszoba_takaritas
          - input_datetime.haloszoba_takaritas
          - input_boolean.konyha_takaritas
          - input_datetime.konyha_takaritas
          - input_boolean.nappali_takaritas
          - input_datetime.nappali_takaritas
        title: Porszívó
      - type: grid
        square: false
        columns: 1
        cards:
          - show_current: true
            show_forecast: true
            type: weather-forecast
            entity: weather.forecast_home
          - show_current: false
            show_forecast: true
            type: weather-forecast
            entity: weather.forecast_home_hourly
      - type: entities
        entities:
          - entity: sensor.kulteri_paratartalom
            icon: mdi:water-percent
          - entity: sensor.kulteri_homerseklet
            icon: mdi:thermometer
          - sensor.kulteri_absolutehumidity
          - sensor.kulteri_dewpoint
          - sensor.kulteri_heatindex
          - sensor.kulteri_simmerindex
          - sensor.kulteri_simmerzone
          - sensor.kulteri_perception
        title: Kültéri
      - type: entities
        entities:
          - entity: sensor.belteri_paratartalom
            icon: mdi:water-percent
          - entity: sensor.belteri_homerseklet
            icon: mdi:thermometer
          - sensor.belteri_absolutehumidity
          - sensor.belteri_dewpoint
          - sensor.belteri_heatindex
          - sensor.belteri_simmerindex
          - sensor.belteri_simmerzone
          - sensor.belteri_perception
        title: Beltéri
      -  type: custom:scheduler-card
         include:
           - binary_sensor.haloszoba_ablak_contact
           - binary_sensor.nappali_ablak_contact
           - climate.honeywell_home_termosztat
           - group.family_gps
           - input_boolean.elofutes
           - sensor.kulteri_homerseklet
         exclude: []
         display_options:
           primary_info: default
           secondary_info:
             - relative-time
             - action

