blueprint:
  name: Bathroom Humidity Management
  description: Fürdőszoba szellőztetés be és kikapcsolás páratartalom érzékelő vagy
    alapérték közötti különbség alapján, figyelembe véve az abszolút páratartalmakat,
    valamint éjszakai szüneteltetést.
  domain: automation
  input:
    humidity_sensor:
      name: Humidity Sensor
      description: Fürdűszoba páratartalom érzékelő
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    absolutehumidity_sensor:
      name: AbsoluteHumidity Sensor
      description: Fürdűszoba abszolút páratartalom érzékelő
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    reference_humidity:
      name: Reference Humidity
      description: Egy százalékpontos érték, amely az alap páratartalmat jelzi, ha
        nem áll rendelkezésre referenciaérzékelő.
      default: 55
    reference_humidity_sensor:
      name: Reference Humidity Sensor
      description: Referencia páratartalom érzékelő.
      selector:
        entity:
          domain:
          - sensor
          multiple: false
      default: []
    outdoor_absolutehumidity_sensor:
      name: Outdoor Absolutehumidity Sensor
      description: Kültéri abszolút páratartalom érzékelő.
      selector:
        entity:
          domain:
          - sensor
          multiple: false
      default: []
    fan_switch:
      name: Fan Switch
      description: A fürdőszoba ventillátor kapcsoló.
      selector:
        entity:
          domain:
          - switch
          multiple: false
    bathroom_window:
      name: Bathroom Window
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - window
          multiple: false
    rising_threshold:
      name: Rising Threshold
      description: Hány százalékponttal emelkedhet az érzékelő a referencia páratartalom
        fölé, mielőtt a ventilátor bekapcsol.
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 1.0
      default: 8
    falling_threshold:
      name: Falling Threshold
      description: Hány százalékponttal kell az érzékelőnek a referencia páratartalom
        fölé csökkennie, mielőtt a ventilátor kikapcsol.
      selector:
        number:
          min: 0.0
          max: 100.0
          mode: slider
          step: 1.0
      default: 5
    time_start:
      name: Fan switch time start
      description: Reggel mikortól figyelje a szellőztető bekapcsolását.
      default: 05:30:00
      selector:
        time: {}
    time_stop:
      name: Fan switch time start
      description: Este mikortól ne kapcsolja be a szellőztetést.
      default: '22:00:00'
      selector:
        time: {}
  source_url: https://gist.github.com/MackoMici/6fdf26c8790fd1d47574ad4b2ab0bac2
variables:
  reference_humidity: !input reference_humidity
  humidity_sensor: !input humidity_sensor
  absolutehumidity_sensor: !input absolutehumidity_sensor
  absolutehumidity: '{{ states(absolutehumidity_sensor) }}'
  reference_humidity_sensor: !input reference_humidity_sensor
  outdoor_absolutehumidity_sensor: !input outdoor_absolutehumidity_sensor
  outdoor_absolutehumidity: '{{ states(outdoor_absolutehumidity_sensor) }}'
  fan_switch: !input fan_switch
  switch_state: '{{ states(fan_switch) }}'
  rising_threshold: !input rising_threshold
  falling_threshold: !input falling_threshold
  difference: '{{ states(humidity_sensor) | float(0) - (states(reference_humidity_sensor)
    | float(0) or reference_humidity | float(0)) }}'
  mode: '{% if switch_state == ''off'' and difference | float(0) > rising_threshold
    | float(0) and outdoor_absolutehumidity | float(0) < absolutehumidity | float(0)
    %} on {% elif switch_state == ''on'' and difference | float(0) > falling_threshold
    | float(0) and outdoor_absolutehumidity | float(0) < absolutehumidity | float(0)
    %} on {% else %} off {% endif %}'
trigger:
- platform: time
  at: !input time_stop
- platform: state
  entity_id: !input humidity_sensor
- platform: state
  entity_id: !input reference_humidity_sensor
- platform: state
  entity_id: !input bathroom_window
action:
- choose:
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input fan_switch
        state: 'on'
      - condition: or
        conditions:
        - condition: time
          after: !input time_stop
          before: !input time_start
        - condition: state
          entity_id: !input bathroom_window
          state: 'on'
    sequence:
    - service: switch.turn_off
      entity_id: !input fan_switch
  - conditions:
    - condition: time
      after: !input time_start
      before: !input time_stop
    - condition: state
      entity_id: !input bathroom_window
      state: 'off'
    - condition: template
      value_template: '{{ mode != switch_state }}'
    sequence:
    - service: switch.turn_{{mode}}
      entity_id: !input fan_switch
mode: single
