blueprint:
  name: Kamra világítás vezérlés
  description: Ajtó nyitásra kapcsolja a világytást valamint tavasztól őszig napközben
    nem kapcsol villanyt
  domain: automation
  input:
    season:
      name: Season
      description: Évszakok érzékelője
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    doorsensor_entity:
      name: Door Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - door
          multiple: false
    doorsensor_light:
      name: Door Light Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - light
          multiple: false
    light_switch:
      name: Light
      selector:
        entity:
          domain:
          - light
          multiple: false
    light_off_wait:
      name: Wait time
      description: Mennyi ideig marad égve a lámpa ha csukott ajtónál valamiért felkapcsol
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
  source_url: https://gist.github.com/MackoMici/5d083fbf325e9c14c975dd5ca1e08609
mode: queued
trigger:
- platform: state
  entity_id: !input doorsensor_entity
  id: Door
- platform: state
  entity_id: !input light_switch
  to: 'on'
  for: !input light_off_wait
  id: Light_on
action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - Door
      - Light_on
    - condition: state
      entity_id: !input doorsensor_entity
      state: 'off'
    - condition: state
      entity_id: !input light_switch
      state: 'on'
    sequence:
    - service: light.turn_off
      entity_id: !input light_switch
  - conditions:
    - condition: trigger
      id: Door
    - condition: state
      entity_id: !input doorsensor_entity
      state: 'on'
    - condition: state
      entity_id: !input season
      state: winter
    sequence:
    - service: light.turn_on
      entity_id: !input light_switch
  - conditions:
    - and:
      - condition: trigger
        id: Door
      - condition: state
        entity_id: !input doorsensor_entity
        state: 'on'
      - or:
        - condition: sun
          before: sunrise
        - condition: time
          after: '12:00:00'
        - condition: state
          entity_id: !input doorsensor_light
          state: 'on'
      - or:
        - condition: state
          entity_id: !input season
          state: spring
        - condition: state
          entity_id: !input season
          state: autumn
    sequence:
    - service: light.turn_on
      entity_id: !input light_switch
  - conditions:
    - condition: trigger
      id: Door
    - condition: state
      entity_id: !input doorsensor_entity
      state: 'on'
    - condition: sun
      after: sunset
      before: sunrise
    - condition: state
      entity_id: !input season
      state: summer
    sequence:
    - service: light.turn_on
      entity_id: !input light_switch
