blueprint:
  name: Tablet Charging
  description: Tablet töltés be/kikapcsolás.
  domain: automation
  input:
    tablet_battery:
      name: Tablet Battery Level
      selector:
        entity:
          domain: sensor
          device_class: battery
    tablet_switch:
      name: Tablet Switch
      selector:
        entity:
          domain: switch
    turn_on:
      name: Tablet Batter minimum
      default: 10
      selector:
        number:
          min: 1.0
          max: 99.0
          mode: slider
          step: 1.0
  source_url: https://gist.github.com/MackoMici/f40e7a9beca216abcdd53bea9be0ca80
mode: single
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input 'tablet_battery'
action:
- choose:
  - conditions:
    - condition: numeric_state
      entity_id: !input 'tablet_battery'
      below: !input 'turn_on'
    - condition: state
      entity_id: !input 'tablet_switch'
      state: 'off'
    sequence:
    - service: switch.turn_on
      target:
        entity_id: !input 'tablet_switch'
      data: {}
  - conditions:
    - condition: state
      entity_id: !input 'tablet_battery'
      state: '100'
    sequence:
    - service: switch.turn_off
      target:
        entity_id: !input 'tablet_switch'
      data: {}
