blueprint:
  name: Turn off Switch after Time has elapsed
  description: Given a switch entity, watch for it turning on, and then turn it off
    after a certain period of time.
  domain: automation
  input:
    switch:
      name: Switch
      description: Select the switch to monitor and control
      selector:
        entity:
          domain: switch
          multiple: false
    time:
      name: Duration
      description: The duration to leave the switch on for
      selector:
        time: {}
  source_url: https://gist.github.com/MackoMici/92a564351c971495abe49b67a48f62c7
trigger:
- platform: state
  entity_id: !input switch
  to: 'on'
  for: !input time
condition: []
action:
- service: switch.turn_off
  data: {}
  entity_id: !input switch
mode: single
