sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /mnt/hdd1
      - type: disk_use_percent
        arg: /mnt/hdd2
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

  - platform: time_date
    display_options:
      - time
      - date

  - platform: template
    sensors:
      devices_with_low_battery:
        friendly_name: 'Devices with Low Battery'
        unit_of_measurement: devices
        value_template: >
          {{ states.sensor | selectattr('attributes.device_class', 'eq', 'battery') | rejectattr('entity_id', 'search', 'battery_level') | map(attribute='state') | reject('in', ['unknown', 'unavailable']) | map('int', -1) | select('le', 30) | select('ge', 0) | list | count }}
        icon_template: >
          {% if is_state('sensor.devices_with_low_battery', 0) %}
            mdi:battery-check
          {% else %}
            mdi:battery-alert
          {% endif %}
